# Generated by Django 5.0.4 on 2024-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_stuff',
            field=models.BooleanField(default=True, verbose_name='сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
