# Generated by Django 5.0.4 on 2024-05-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('product_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='продуктовая модель')),
                ('launch_date', models.DateField(verbose_name='дата выхода товара на рынок')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_level', models.CharField(choices=[(0, 'Производитель'), (1, 'Продает другому поставщику'), (2, 'Продает потребителю')], verbose_name='уровень структуры')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название.')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='дом')),
                ('debt_to_supplier', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Задолженность перед поставщиком с точностью до копеек')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Время создания(заполняется автоматически при создании)')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.networklink', verbose_name='поставщик')),
                ('product', models.ManyToManyField(to='main.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'звено сети по продаже электроники',
                'verbose_name_plural': 'звенья сети по продаже электроники',
            },
        ),
    ]
