# Generated by Django 5.0.4 on 2024-05-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_networklink_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networklink',
            name='network_level',
            field=models.CharField(choices=[(0, 'Производитель'), (2, 'Продает потребителю'), (1, 'Продает другому поставщику')], verbose_name='уровень структуры'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.networklink', verbose_name='поставщик'),
        ),
    ]
