# Generated by Django 5.0.4 on 2024-05-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_networklink_network_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networklink',
            name='network_level',
            field=models.CharField(choices=[(0, 'Производитель'), (1, 'Продает другому поставщику'), (2, 'Продает потребителю')], verbose_name='уровень структуры'),
        ),
    ]
