# Generated by Django 4.2.10 on 2024-05-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_networklink_network_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networklink',
            name='network_level',
            field=models.CharField(choices=[(0, 'Поставщик - производитель'), (1, 'Поставщик - розничная сеть'), (2, 'Поставщик - продавец потребителю')], verbose_name='уровень структуры'),
        ),
        migrations.AlterField(
            model_name='networklink',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='products_networklink', to='main.product', verbose_name='продукт'),
        ),
    ]
